 pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Packaging stage"'  
        }
      }  
    }

    stage ('Deployment') {
      steps {
        script {
          sh 'echo "This is Deployment stage"'  
        }
      }  
    }

    stage ('clean workspace') {
      steps {
        script {
          sh 'echo "This is cleaning stage"'  
        }
      }  
    }
    }
}
